version: '2.4'
services:
  jira-web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jira-web
    ports:
      - 8080:8080
    mem_limit: 2048m
    mem_reservation: 1024m
    memswap_limit: 2048m
     environment:
       CATALINA_OPTS: -Xms2048m -Xmx4096m -Datlassian.plugins.enable.wait=300
       X_PROXY_NAME: domain.com
       X_PROXY_SCHEME: https
       X_PROXY_PORT: 443
    volumes:
      - web:/var/atlassian/jira
    links:
      - jira-db
  jira-db:
    restart: always
    image: mysql:5.7
    container_name: jira-db
    # ports:
    #  - 3306:3306
    mem_limit: 1024m
    mem_reservation: 256m
    memswap_limit: 512m
    environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: jira_db
       MYSQL_USER: jira_user
       MYSQL_PASSWORD: password
    volumes:
        - db:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_bin']
volumes:
    web:
    db:
